version: "3.4"
services:
  app:
    image: pd-advent2022:latest
    restart: unless-stopped
    networks:
      - traefik_public
    labels:
      - "traefik.http.routers.advent.rule=Host(`advent.davlin.io`)"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.advent.loadbalancer.server.port=3000"
      - "traefik.http.routers.advent.entrypoints=https"
      - "traefik.http.routers.advent.tls=true"

networks:
  traefik_public:
    external: true
